
services:
  - type: web
    name: messenger-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --workers 2 --timeout 30
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: VERIFY_TOKEN
        sync: false
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
